name: Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - uses: dlang-community/setup-dlang@v2
        with:
          compiler: ldc-latest
      - name: Build library
        run: dub build
      - name: Test
        run: dub test
      - name: Example
        run: dub build --root=examples/echo